version: 2.1

orbs:
  node: circleci/node@2.1.1

jobs:
  build-and-test-COLONY:
    executor:
      name: node/default
      tag: '10.20'
    steps:
      - checkout
      - setup_remote_docker
      - run: yarn bootstrap
      - run: npx truffle obtain --solc=0.5.16
      - run: COLONY=true yarn ci

  build-and-test-COVERAGE:
    executor:
      name: node/default
      tag: '8.17'
    steps:
      - checkout
      - setup_remote_docker
      - run: yarn bootstrap
      - run: npx truffle obtain --solc=0.5.16
      - run: COVERAGE=true yarn ci

workflows:
  build-and-test:
    jobs:
      - build-and-test-COLONY:
          filters:
            branches:
              only:
                - develop
      - build-and-test-COVERAGE:
          filters:
            branches:
              only:
                # long-lived branches
                - master
                - develop
                - next

                # other targets
                - truffle-db
                - travis-to-circle-coverage
